### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Lcyby** [bitextor/bleualign-cpp#12]
**'make -j4'  Display this error**

[ 87%] No update step for 'googletest'
[ 88%] No patch step for 'googletest'
[ 89%] Performing configure step for 'googletest'
-- googletest configure command succeeded.  See also /home/liuxy/bleualign-cpp-master/build/gtest/src/googletest-stamp/googletest-configure-*.log
[ 90%] Performing build step for 'googletest'
CMake Error at /home/liuxy/bleualign-cpp-master/build/gtest/src/googletest-stamp/googletest-build-Release.cmake:49 (message):
  Command failed: 2

   'make'

  See also

    /home/liuxy/bleualign-cpp-master/build/gtest/src/googletest-stamp/googletest-build-*.log

make[2]: *** [gtest/src/googletest-stamp/googletest-build] Error 1
make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
make: *** [all] Error 2

**Comment by zuny26** [comment]
Hi @Lcyby 
Seems to be something wrong with GTest, although from the error it is not clear to me what it is. Try disabling tests:
```
cmake .. -DBUILD_TEST=off -DCMAKE_BUILD_TYPE=Release
make -j4
```

**Comment by lpla** [comment]
Unable to reproduce. Please reopen if necessary.
